# spring.application.name=student_management_system_be

# spring.datasource.url=jdbc:mysql://localhost:3306/student_management_system?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

spring.application.name=student_management_system_be

spring.datasource.url=jdbc:sqlite:student_management_system.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true